// Los recursos de Script han cambiado para la v2.3.0 Consulta
// https://help.yoyogames.com/hc/en-us/articles/360005277377 para más información
function AddBossDemonCollection()
{
	ds_map_add(global.collectionList, global.totalNumberOfVinyls,
	{ 
		alias: "bossDemon",
		song: snd_songDemon,
		songBSide: snd_obsession,
		offsetSong: 0,
		offsetSongBSide: 0,
		keyKilledBy :"killedByDemon",
		sprite: s_bossDemon,
		spriteMain: s_bossDemon,
		spriteBSide: s_bossDemon_B,
		spriteVinyl: s_discoVinilo,
		hpMax: 130,
		vinylAlpha : 0.85,
		vinylAlphaBSide: 0.85,
		vinylColor : global.lightBlue,
		vinylColorBSide: global.lightPink,
		number: 1,
		defeatedInRun: 0,
		collection: global.bossDemonCollection,
		unlocked: 0,
		step:  BossDemonStep,
		tintCol: global.yellowArray,
		noiseTintCol: global.BlueArray,
		tintColBSide: global.lightBlueArray3,
		noiseTintColBSide: global.lightPinkArray,
		wallSprite: s_wallDemon,
		isDLC: false,
		spriteDLCTitle: s_elGancho_title,
		songName: "Ay Ay Ay (No Tomorrow)",
		songNameBSide: "Really-Here (b-side)",
		albumName: "SPYYN OST",
		artistName: "ESE UVE",
		killsName: "bossDemonKills",
		deathsName: "bossDemonDeaths",
		killsNameBSide: "bossDemonKillsBSide",
		deathsNameBSide: "bossDemonDeathsBSide",
		kills: 0,
		deaths: 0,
		killsBSide: 0,
		deathsBSide: 0,
		minKillsBSide: 6,
	})

	global.totalNumberOfVinyls +=1;
}
