// Los recursos de Script han cambiado para la v2.3.0 Consulta
// https://help.yoyogames.com/hc/en-us/articles/360005277377 para más información
function AddBossRataCollection()
{
	ds_map_add(global.collectionList, global.totalNumberOfVinyls,
	{ 
		alias: "bossRata",
		song: snd_chino,
		songBSide: snd_ritual,
		offsetSong: 5,
		offsetSongBSide: 0,
		keyKilledBy :"killedByRata",
		sprite: s_bossRata,
		haveBSide: true,
		spriteMain: s_bossRata,
		spriteBSide: s_bossRata_B,
		spriteVinyl: s_discoVinilo,
		hpMax: 290,
		vinylAlpha : 0.85,
		vinylAlphaBSide: 0.85,
		vinylColor : global.greenRat,
		vinylColorBSide: global.lightBlue,
		number: 4,
		defeatedInRun: 0,
		collection: global.bossRataCollection,
		unlocked: 0,
		step: BossRataStep,
		tintCol: global.greenOscRatArray,
		noiseTintCol: global.greenRatArray,
		tintColBSide: global.BlueArray,
		noiseTintColBSide: global.brightArray,
		wallSprite: s_wallRata,
		wallSpriteBSide: s_wallRata_B,
		isDLC: false,
		spriteDLCTitle: s_elGancho_title,
		songName: "ratrat",
		albumName: "SPYYN OST",
		songNameBSide: "Ritual (b-side)",
		artistName: "ESE UVE",
		killsName: "bossRataKills",
		deathsName: "bossRataDeaths",
		killsNameBSide: "bossRataKillsBSide",
		deathsNameBSide: "bossRataDeathsBSide",
		kills: 0,
		deaths: 0,
		killsBSide: 0,
		deathsBSide: 0,
		minKillsBSide: 9,
	})

	global.totalNumberOfVinyls +=1;
}
