// Los recursos de Script han cambiado para la v2.3.0 Consulta
// https://help.yoyogames.com/hc/en-us/articles/360005277377 para más información
function AddBossUpgradesCollection()
{
	ds_map_add(global.collectionList, global.totalNumberOfVinyls,
	{ 
		alias: "bossUpgrades",
		song: snd_upgrade,
		songBSide: snd_missU,
		offsetSong: 0,
		offsetSongBSide: 0,
		keyKilledBy :"killedByUpgrades",
		sprite: s_galletaUpgrades,
		haveBSide: true,
		spriteMain: s_galletaUpgrades,
		spriteBSide: s_galletaUpgrades_B,
		spriteVinyl: s_discoVinilo,
		hpMax: 444,
		vinylAlpha : 0.9,
		vinylAlphaBSide: 0.85,
		vinylColor : global.lightPink,
		vinylColorBSide: global.pink,
		number: 6,
		defeatedInRun: 0,
		collection: global.bossUpgradesCollection,
		unlocked: -4,
		step: BossGirlStep,
		tintCol: global.brightArray,
		noiseTintCol: global.lightPinkArray,
		tintColBSide: global.pinkArray2,
		noiseTintColBSide: global.brightArray,
		wallSprite: s_wallNacho,
		wallSpriteBSide: s_wallNacho,
		isDLC: false,
		spriteDLCTitle: s_elGancho_title,
		songName: "Love Spell",
		songNameBSide: "Miss U (b-side)",
		albumName: "Paradxse",
		artistName: "SV",
		killsName: "bossUpgradesKills",
		deathsName: "bossUpgradesDeaths",
		killsNameBSide: "bossUpgradesKillsBSide",
		deathsNameBSide: "bossUpgradesDeathsBSide",
		kills: 0,
		deaths: 0,
		killsBSide: 0,
		deathsBSide: 0,
		minKillsBSide: 10,
	})

	global.totalNumberOfVinyls +=1;
}