// Los recursos de Script han cambiado para la v2.3.0 Consulta
// https://help.yoyogames.com/hc/en-us/articles/360005277377 para más información
function AddBossTribalCollection()
{
	ds_map_add(global.collectionList, global.totalNumberOfVinyls,
	{ 
		alias: "bossTribal",
		song: snd_tribal,
		songBSide: snd_hellIsHome,
		offsetSongBSide: 48,
		offsetSong: 135,
		keyKilledBy :"killedByTribal",
		sprite: s_bossTribal,
		haveBSide: true,
		spriteMain: s_bossTribal,
		spriteBSide: s_bossTribal_B,
		spriteVinyl: s_discoVinilo,
		hpMax: 200,
		vinylAlpha : 0.98,
		vinylAlphaBSide: 0.95,
		vinylColor : global.yellow,
		vinylColorBSide: global.greenOscRat,
		number: global.totalNumberOfVinyls,
		defeatedInRun: 0,
		collection: global.bossTribalCollection,
		unlocked: 0,
		step: BossTribalStep,
		tintCol: [0, 0, 0, 1],
		noiseTintCol: global.yellowArray2,
		tintColBSide: global.darkPaletteArray,
		noiseTintColBSide: global.greenRatArray,
		wallSprite: s_wallTribal,
		wallSpriteBSide: s_wallTribal_B,
		isDLC: false,
		spriteDLCTitle: s_elGancho_title,
		songName: "Nothing Inside You",
		songNameBSide: "Hell Is Home (b-side)",
		albumName: "SPYYN OST",
		artistName: "ESE UVE",
		killsName: "bossTribalKills",
		deathsName: "bossTribalDeaths",
		killsNameBSide: "bossTribalKillsBSide",
		deathsNameBSide: "bossTribalDeathsBSide",
		kills: 0,
		deaths: 0,
		killsBSide: 0,
		deathsBSide: 0,
		minKillsBSide: 3,
	})

	global.totalNumberOfVinyls +=1;
}
