// Los recursos de Script han cambiado para la v2.3.0 Consulta
// https://help.yoyogames.com/hc/en-us/articles/360005277377 para más información
function AddBossRombossCollection()
{
	ds_map_add(global.collectionList, global.totalNumberOfVinyls,
	{ 
		alias: "bossRomboss",
		song: snd_Romboss,
		songBSide: snd_obsession,
		offsetSong: 36,
		offsetSongBSide: 0,
		keyKilledBy :"killedByRomboss",
		sprite: s_bossRomboss,
		haveBSide: false,
		spriteMain: s_bossRomboss,
		spriteBSide: s_bossNacho_B,
		spriteVinyl: s_discoVinilo,
		hpMax: 550,
		vinylAlpha : 0.85,
		vinylAlphaBSide: 0.75,
		vinylColor : global.blue,
		vinylColorBSide: global.lightBlue,
		number: global.totalNumberOfVinyls,
		defeatedInRun: 0,
		collection: global.bossRombossCollection,
		unlocked: 0,
		step: BossRombossStep,
		tintCol: global.BlueArray,
		noiseTintCol: global.lightBlueArray,
		tintColBSide: global.BlueArray,
		noiseTintColBSide: global.salmonArray,
		wallSprite: s_wallDemon,
		wallSpriteBSide: s_wallGirl_B,
		isDLC: true,
		spriteDLCTitle: s_elGancho_title,
		songName: "Crystal Boss",
		songNameBSide: "Broken Crystal (b-side)",
		albumName: "El Gancho OST",
		artistName: "Ingala",
		killsName: "bossRombossKills",
		deathsName: "bossRombossDeaths",
		killsNameBSide: "bossRombossKillsBSide",
		deathsNameBSide: "bossRombossDeathsBSide",
		kills: 0,
		deaths: 0,
		killsBSide: 0,
		deathsBSide: 0,
		minKillsBSide: 10,
	})

	global.totalNumberOfVinyls +=1;
}
