// Los recursos de Script han cambiado para la v2.3.0 Consulta
// https://help.yoyogames.com/hc/en-us/articles/360005277377 para más información
function AddBossGirlCollection()
{
	ds_map_add(global.collectionList, global.totalNumberOfVinyls,
	{ 
		alias: "bossGirl",
		song: snd_e4u,
		songBSide: snd_obsession,
		offsetSong: 40,
		offsetSongBSide: 0,
		keyKilledBy :"killedByGirl",
		sprite: s_bossGirl,
		haveBSide: true,
		spriteMain: s_bossGirl,
		spriteBSide: s_bossGirl_B,
		spriteVinyl: s_discoVinilo,
		hpMax: 270,
		vinylAlpha : 0.95,
		vinylAlphaBSide : 0.8,
		vinylColor : global.pink,
		vinylColorBSide: global.lightPink,
		number: global.totalNumberOfVinyls,
		defeatedInRun: 0,
		collection: global.bossGirlCollection,
		unlocked: 0,
		step: BossGirlStep,
		tintCol: global.purpleArray,
		noiseTintCol: global.yellowGirlArray,
		tintColBSide: global.purpleArray,
		noiseTintColBSide: global.darkPaletteArray,
		wallSprite: s_wallGirl,
		wallSpriteBSide: s_wallGirl_B,
		isDLC: false,
		spriteDLCTitle: s_elGancho_title,
		songName: "Enough 4 U",
		songNameBSide: "Really-Here (b-side)",
		albumName: "SPYYN OST",
		artistName: "ESE UVE",
		killsName: "bossGirlKills",
		deathsName: "bossGirlDeaths",
		killsNameBSide: "bossGirlKillsBSide",
		deathsNameBSide: "bossGirlDeathsBSide",
		kills: 0,
		deaths: 0,
		killsBSide: 0,
		deathsBSide: 0,
		minKillsBSide: 4,
	})

	global.totalNumberOfVinyls +=1;
}
