// Los recursos de Script han cambiado para la v2.3.0 Consulta
// https://help.yoyogames.com/hc/en-us/articles/360005277377 para más información
function AddBossOblongCollection()
{
	ds_map_add(global.collectionList, global.totalNumberOfVinyls,
	{ 
		alias: "bossOblong",
		song: snd_Reset3,
		songBSide: snd_obsession,
		offsetSong: 14,
		offsetSongBSide: 0,
		keyKilledBy :"killedByOblong",
		sprite: s_bossOblong,
		haveBSide: false,
		spriteMain: s_bossOblong,
		spriteBSide: s_bossNacho_B,
		spriteVinyl: s_discoVinilo,
		hpMax: 400,
		vinylAlpha : 0.95,
		vinylAlphaBSide: 0.75,
		vinylColor : global.orange,
		vinylColorBSide: global.lightBlue,
		number: 9,
		defeatedInRun: 0,
		collection: global.bossBigEyeCollection,
		unlocked: 0,
		step: BossOblongStep,
		tintCol: global.yellowArray2,
		noiseTintCol: global.orangeArray,
		tintColBSide: global.BlueArray,
		noiseTintColBSide: global.salmonArray,
		wallSprite: s_wallOblong,
		wallSpriteBSide: s_wallGirl_B,
		isDLC: true,
		spriteDLCTitle: s_elGancho_title,
		songName: "Reset.3",
		songNameBSide: "Hope.3 (b-side)",
		albumName: "El Gancho OST",
		artistName: "Ingala",
		killsName: "bossOblongKills",
		deathsName: "bossOblongDeaths",
		killsNameBSide: "bossOblongKillsBSide",
		deathsNameBSide: "bossOblongDeathsBSide",
		kills: 0,
		deaths: 0,
		killsBSide: 0,
		deathsBSide: 0,
		minKillsBSide: 10,
	})

	global.totalNumberOfVinyls +=1;
}
