// Los recursos de Script han cambiado para la v2.3.0 Consulta
// https://help.yoyogames.com/hc/en-us/articles/360005277377 para más información
function AddBossBigEyeCollection()
{
	ds_map_add(global.collectionList, global.totalNumberOfVinyls,
	{ 
		alias: "bossBigEye",
		song: snd_EyeSeeU,
		songBSide: snd_obsession,
		offsetSong: 14,
		offsetSongBSide: 0,
		keyKilledBy :"killedByBigEye",
		sprite: s_bossBigEye,
		haveBSide: false,
		spriteMain: s_bossBigEye,
		spriteBSide: s_bossBigEye,
		spriteVinyl: s_discoVinilo,
		hpMax: 500,
		vinylAlpha: 0.95,
		vinylAlphaBSide: 0.75,
		vinylColor: global.lightPink,
		vinylColorBSide: global.lightBlue,
		number: 7,
		defeatedInRun: 0,
		collection: global.bossBigEyeCollection,
		unlocked: 0,
		step: BossBigEyeStep,
		tintCol: global.purpleArray,
		noiseTintCol: global.salmonArray,
		tintColBSide: global.purpleArray,
		noiseTintColBSide: global.salmonArray,
		wallSprite: s_wallBigEye,
		wallSpriteBSide: s_wallBigEye,
		isDLC: true,
		spriteDLCTitle: s_elGancho_title,
		songName: "Eye See U",
		songNameBSide: "Really-Here (b-side)",
		albumName: "El Gancho OST",
		artistName: "Ingala",
		killsName: "bossBigEyeKills",
		deathsName: "bossBigEyeDeaths",
		killsNameBSide: "bossBigEyeKillsBSide",
		deathsNameBSide: "bossBigEyeDeathsBSide",
		kills: 0,
		deaths: 0,
		killsBSide: 0,
		deathsBSide: 0,
		minKillsBSide: 10,
	})

	global.totalNumberOfVinyls +=1;
}
