// Los recursos de Script han cambiado para la v2.3.0 Consulta
// https://help.yoyogames.com/hc/en-us/articles/360005277377 para más información
function AddBossPentagovonCollection()
{
	ds_map_add(global.collectionList, global.totalNumberOfVinyls,
	{ 
		alias: "bossPentagovon",
		song: snd_satansVomit,
		songBSide: snd_obsession,
		offsetSong: 0,
		offsetSongBSide: 0,
		keyKilledBy :"killedByPentagovon",
		sprite: s_bossPentagovon,
		haveBSide: false,
		spriteMain: s_bossPentagovon,
		spriteBSide: s_bossNacho_B,
		spriteVinyl: s_discoVinilo,
		hpMax: 666,
		vinylAlpha : 0.95,
		vinylAlphaBSide: 0.75,
		vinylColor : global.brightRed,
		vinylColorBSide: global.lightBlue,
		number: global.totalNumberOfVinyls,
		defeatedInRun: 0,
		collection: global.bossPentagovonCollection,
		unlocked: 0,
		step: BossPentagovonStep,
		tintCol: global.redArray,
		noiseTintCol: global.yellowArray,
		tintColBSide: global.BlueArray,
		noiseTintColBSide: global.salmonArray,
		wallSprite: s_wallPentagovon,
		wallSpriteBSide: s_wallGirl_B,
		isDLC: true,
		spriteDLCTitle: s_elGancho_title,
		songName: "Satan's Vomit",
		songNameBSide: "Showoff (b-side)",
		albumName: "El Gancho OST",
		artistName: "Ingala",
		killsName: "bossPentagovonKills",
		deathsName: "bossPentagovonDeaths",
		killsNameBSide: "bossOblongKillsBSide",
		deathsNameBSide: "bossOblongDeathsBSide",
		kills: 0,
		deaths: 0,
		killsBSide: 0,
		deathsBSide: 0,
		minKillsBSide: 10,
	})

	global.totalNumberOfVinyls +=1;
}
